  name: helloworld_workflow
  on:
    push:
      branches:
        - main
    pull_requests:
      branches:
        - main:
    workflow_dispatch:
  
  jobs:
    hello:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout:v2
        - name: Helloworld
          run: echo "hello world"
          shell: bash
