name: test1

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@V2
      - name: bashrun
        run: df -h
        shell: bash
